# Generated by Django 3.2.25 on 2025-12-04 13:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20251001_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã voucher (VD: NEWUSER2025)', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Mô tả voucher')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('freeship', 'Free Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm (% hoặc số tiền)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Đơn hàng tối thiểu để áp dụng voucher', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Giảm tối đa (chỉ cho % discount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quantity', models.IntegerField(default=0, help_text='Tổng số lượng voucher (0 = không giới hạn)', validators=[django.core.validators.MinValueValidator(0)])),
                ('used_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_user_limit', models.IntegerField(default=1, help_text='Số lần mỗi user có thể dùng (0 = không giới hạn)', validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(help_text='Ngày bắt đầu có hiệu lực')),
                ('end_date', models.DateTimeField(help_text='Ngày hết hạn')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Usage',
                'verbose_name_plural': 'Voucher Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'User Voucher',
                'verbose_name_plural': 'User Vouchers',
                'ordering': ['-collected_at'],
                'unique_together': {('user', 'voucher')},
            },
        ),
    ]
