# Generated by Django 3.2.25 on 2025-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20251001_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_discount',
            field=models.FloatField(default=0),
        ),
    ]
